### ISSUE TITLE
Create a run error

### ISSUE THREAD

**Issue by rjmatias** [RageAgainstThePixel/OpenAI-DotNet#178]
Hello!

Trying to create a chat bot with this parser and CreateMessageAsync always throw an error "The JSON property name for 'OpenAI.Threads.FileCitation.file_id' collides with another property."

Snippet 
private static async Task<string> testingAPI(OpenAIClient openAIClient)
 {
     var assistant = await openAIClient.AssistantsEndpoint.CreateAssistantAsync(
         new CreateAssistantRequest(
             name: "Math Tutor",
             instructions: "You are a personal math tutor. Answer questions briefly, in a sentence or less.",
             model: "gpt-4-1106-preview"));
     var thread = await openAIClient.ThreadsEndpoint.CreateThreadAsync();
     var message = await thread.CreateMessageAsync("I need to solve the equation `3x + 11 = 14`. Can you help me?");
     var run = await thread.CreateRunAsync(assistant);
     Console.WriteLine($"[{run.Id}] {run.Status} | {run.CreatedAt}");
     return message;
 }

I tried some other methods of creating a message and all throw the same error. 

The error occurs when calling CreateMessageAsync.

**Comment by StephenHodgson** [comment]
Is this the same snippet from the unit tests?

**Comment by rjmatias** [comment]
Yeap!
The only difference is this 
var thread = await openAIClient.ThreadsEndpoint.CreateThreadAsync();

because it gives the error "An object reference is required for the non-static field, method, or property 'OpenAIClient.ThreadsEndpoint'" so I'm passing the a new instance of OpenAiClient	
snippet unit test is:
var thread = await OpenAIClient.ThreadsEndpoint.CreateThreadAsync();

**Comment by StephenHodgson** [comment]
Enable debug mode and post the output

**Comment by rjmatias** [comment]
{"model":"gpt-4-1106-preview","name":"Math Tutor","instructions":"You are a personal math tutor. Answer questions briefly, in a sentence or less."}
{
  "id": "asst_VDGFqX1dlYsoqWSgv1RBDRY2",
  "object": "assistant",
  "created_at": 1700699756,
  "name": "Math Tutor",
  "description": null,
  "model": "gpt-4-1106-preview",
  "instructions": "You are a personal math tutor. Answer questions briefly, in a sentence or less.",
  "tools": [],
  "file_ids": [],
  "metadata": {}
}
{
  "id": "thread_TVGYX5Vd98qKwOsgkEoxZwIQ",
  "object": "thread",
  "created_at": 1700699757,
  "metadata": {}
}
{"role":"user","content":"I need to solve the equation \u00603x \u002B 11 = 14\u0060. Can you help me?"}
{
  "id": "msg_b2DzP6F0cUogdSpizWDVWwW1",
  "object": "thread.message",
  "created_at": 1700699758,
  "thread_id": "thread_TVGYX5Vd98qKwOsgkEoxZwIQ",
  "role": "user",
  "content": [
    {
      "type": "text",
      "text": {
        "value": "I need to solve the equation `3x + 11 = 14`. Can you help me?",
        "annotations": []
      }
    }
  ],
  "file_ids": [],
  "assistant_id": null,
  "run_id": null,
  "metadata": {}
}
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: The JSON property name for 'OpenAI.Threads.FileCitation.file_id' collides with another property.
         at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerPropertyNameConflict(Type type, String propertyName)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.JsonPropertyInfoList.AddPropertyWithConflictResolution(JsonPropertyInfo jsonPropertyInfo, PropertyHierarchyResolutionState& state)
         at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.AddMembersDeclaredBySuperType(JsonTypeInfo typeInfo, Type currentType, Boolean constructorHasSetsRequiredMembersAttribute, PropertyHierarchyResolutionState& state)
         at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.PopulateProperties(JsonTypeInfo typeInfo)
         at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.CreateTypeInfoCore(Type type, JsonConverter converter, JsonSerializerOptions options)
         at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetTypeInfo(Type type, JsonSerializerOptions options)
         at System.Text.Json.JsonSerializerOptions.GetTypeInfoNoCaching(Type type)
         at System.Text.Json.JsonSerializerOptions.CachingContext.CreateCacheEntry(Type type, CachingContext context)
      --- End of stack trace from previous location ---
         at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType)
         at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure()
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ConfigureProperties()
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|172_0()
         at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|172_0()
         at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType)
         at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure()
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ConfigureProperties()
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|172_0()
         at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType)
         at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure()
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ConfigureProperties()
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|172_0()
         at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|172_0()
         at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType)
         at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure()
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ConfigureProperties()
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|172_0()
         at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType)
         at System.Text.Json.JsonSerializerOptions.GetTypeInfoForRootType(Type type, Boolean fallBackToNearestAncestorType)
         at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
         at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
         at OpenAI.Extensions.ResponseExtensions.Deserialize[T](HttpResponseMessage response, String json, OpenAIClient client)
         at OpenAI.Threads.ThreadsEndpoint.CreateMessageAsync(String threadId, CreateMessageRequest request, CancellationToken cancellationToken)
         at OpenAI.Threads.ThreadExtensions.CreateMessageAsync(ThreadResponse thread, CreateMessageRequest request, CancellationToken cancellationToken)
         at Chat.Controllers.HomeController.testingAPI() in C:\Work.2023\Blazor\ChatDemo\Chat\Controllers\HomeController.cs:line 159
         at Chat.Controllers.HomeController.ChatMessage(String threadId, String message) in C:\Work.2023\Blazor\ChatDemo\Chat\Controllers\HomeController.cs:line 41
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by StephenHodgson** [comment]
Weird I don't see `file_id` anywhere in your last response.

Also interesting to see the null and empty values in the json.

**Comment by MahirMuzahid** [comment]
Getting the same error with this code:
` var message = await _thisThread.CreateMessageAsync(msg);`

**Comment by kikaragyozov** [comment]
Getting the same error here as well.

**Comment by kikaragyozov** [comment]
[This is the root of the problem.](https://github.com/RageAgainstThePixel/OpenAI-DotNet/blame/271c374ba9b0b5b37aa08f7c409381a0f0b8ae1f/OpenAI-DotNet/Threads/FileCitation.cs#L19)

I'll create a pull request in a bit if there isn't already one.
