### ISSUE TITLE
invalid_request_error in CreateMessageAsync Method

### ISSUE THREAD

**Issue by MahirMuzahid** [RageAgainstThePixel/OpenAI-DotNet#181]
# Bug Report

## Overview
Getting invalid_request_error when I am running this code:
```csharp
var message = await _thisThread.CreateMessageAsync(msg);
```

[Project is updated to 7.3.3]

error:
```
RetrieveMessageAsync Failed! HTTP status code: NotFound | Response body: {
  "error": {
    "message": "No message found with id 'run_U0I9N50YxD6yvX7e0e4m8SsT'.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

**Comment by StephenHodgson** [comment]
I need a better repro. Unit tests are in place to prevent this.

**Comment by MahirMuzahid** [comment]
This is StackTrace

`at OpenAI.Extensions.ResponseExtensions.<ReadAsStringAsync>d__12.MoveNext()
   at OpenAI.Threads.ThreadsEndpoint.<RetrieveMessageAsync>d__9.MoveNext()
   at OpenAI.Threads.ThreadExtensions.<RetrieveMessageAsync>d__6.MoveNext()
   at Oturan_Bot_Controller.Oturan.<RunChat>d__15.MoveNext() in C:\Users\muzah\source\repos\Oturan_Bot_Controller\Oturan.cs:line 63
   at Oturan_Bot_Controller.Oturan.<StartChat>d__11.MoveNext() in C:\Users\muzah\source\repos\Oturan_Bot_Controller\Oturan.cs:line 39`

**Comment by StephenHodgson** [comment]
please provide repro steps or a unit test that fails. I'll reopen when provided.
