### ISSUE TITLE
Some OpenAI API compatible services are using milliseconds epoch causing an overflow

### ISSUE THREAD

**Issue by AlisaAkiron** [RageAgainstThePixel/OpenAI-DotNet#314]
# Bug Report

## Overview

I am using Cloudflare Workers AI with its OpenAI compatible API. Cloudflare is using milliseconds epoch for the created property. For example, this the response from Cloudflare Workers AI:

``` json
{
    "id": "SOME_ID",
    "object": "chat.completion",
    "created": 1717123500573,
    "model": "@cf/meta/llama-3-8b-instruct",
    "choices": [
        {
            "index": 0,
            "message": {
                "role": "assistant",
                "content": "SOME_CONTENT"
            },
            "logprobs": null,
            "finish_reason": "stop"
        }
    ]
}
```

The `ChatResponse` model expect a seconds epoch and Int32 for this property, a milliseconds epoch will cause an overflow.

https://github.com/RageAgainstThePixel/OpenAI-DotNet/blob/03bdded1ab3727d19b90e7d684329699f7478ee6/OpenAI-DotNet/Chat/ChatResponse.cs#L30-L35

Not only the `ChatResponse` model has this problem, but also other response models who have this property.

My suggestions:

1. Change this property to `public ulong CreatedAtUnixTime { get; private set; }` as we don't known which kind of epoch the custom services are using, use ulong can get the max compatibility and let the user to figure it out
2. OR: Let the user to override the response type or and a method that just return the raw response

## To Reproduce

1. Follow [Cloudflare Workers AI](https://developers.cloudflare.com/workers-ai/get-started/rest-api/) documentation to create an access token and get your account id
4. Run the following code

``` c#
var auth = new OpenAIAuthentication("YOUR_CLOUDFLARE_ACCESS_TOKEN");
var option = new OpenAIClientSettings("https://api.cloudflare.com/client/v4/accounts/YOUR_CLOUDFLARE_ACCOUNT_ID/ai");

var openai = new OpenAIClient(auth, option);

var chat = await openai.ChatEndpoint.GetCompletionAsync(new ChatRequest(new List<Message>
{
    new(Role.User, "Hello, please introduce yourself.")
}, model: "@cf/meta/llama-3-8b-instruct", responseFormat: ChatResponseFormat.Text));
```

5. Get the error:

```
Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.created | LineNumber: 0 | BytePositionInLine: 75.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.ThrowHelper.ThrowFormatException(NumericType numericType)
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at OpenAI.Extensions.ResponseExtensions.Deserialize[T](HttpResponseMessage response, String json, OpenAIClient client)
   at OpenAI.Chat.ChatEndpoint.GetCompletionAsync(ChatRequest chatRequest, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in {THE_FILE_PATH} 15
   at Program.<Main>(String[] args)
```

## Expected behavior

No exception should be thrown.

## Additional context

Cloudflare Workers AI OpenAI compatible API endpoints documentation: https://developers.cloudflare.com/workers-ai/configuration/open-ai-compatibility/

**Comment by StephenHodgson** [comment]
Sounds like you need to open a bug report with cloudflare
