### ISSUE TITLE
Proxy throws exception on non-Latin characters

### ISSUE THREAD

**Issue by SamKr** [RageAgainstThePixel/OpenAI-DotNet#57]
Thanks for your hard work! ❤️

For the bug, when sending a chatprompt like:

`how do you say hello in Greek`

The response should be:

`The word for "hello" in Greek is "Χαίρετε" (pronounced as "Hei-re-te").`

This works just fine when using a direct connection to OpenAI.

However, with the proxy in between, I get an `HttpRequestException` exception:

`Error while copying content to a stream.` 

This is most likely caused by the encoding, because when asked:

`how do you say hello in French`

It correctly replies:

`"Bonjour" is the way to say hello in French.`

**Comment by StephenHodgson** [comment]
I need some suggestions on how to accomplish this.

Should I add optional parameter for text encoding?

**Comment by SamKr** [comment]
I'll see what I can do later, but for anyone who's bored, here's the full stacktrace:

```csharp
System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Received chunk header length could not be parsed: '7B-22-69-64-22-3A-22-63-68-61-74-63-6D-70-6C-2D-36-77-57-73-63-74-53-61-74-6A-53-46-47-6F-36-77-38-49-49-61-61-67-61-6F-58-70-72-7A-36-22-2C-22-6F-62-6A-65-63-74-22-3A-22-63-68-61-74-2E-63-6F-6D-70-6C-65-74-69-6F-6E-22-2C-22-63-72-65-61-74-65-64-22-3A-31-36-37-39-34-30-37-34-33-34-2C-22-6D-6F-64-65-6C-22-3A-22-67-70-74-2D-33-2E-35-2D-74-75-72-62-6F-2D-30-33-30-31-22-2C-22-75-73-61-67-65-22-3A-7B-22-70-72-6F-6D-70-74-5F-74-6F-6B-65-6E-73-22-3A-32-31-34-2C-22-63-6F-6D-70-6C-65-74-69-6F-6E-5F-74-6F-6B-65-6E-73-22-3A-32-38-2C-22-74-6F-74-61-6C-5F-74-6F-6B-65-6E-73-22-3A-32-34-32-7D-2C-22-63-68-6F-69-63-65-73-22-3A-5B-7B-22-6D-65-73-73-61-67-65-22-3A-7B-22-72-6F-6C-65-22-3A-22-61-73-73-69-73-74-61-6E-74-22-2C-22-63-6F-6E-74-65-6E-74-22-3A-22-54-68-65-20-77-6F-72-64-20-66-6F-72-20-5C-22-68-65-6C-6C-6F-5C-22-20-69-6E-20-47-72-65-65-6B-20-69-73-20-5C-22-CE-A7-CE-B1-CE-AF-CF-81-CE-B5-CF-84-CE-B5-5C-22-20-28-70-72-6F-6E-6F-75-6E-63-65-64-20-5C-22-6B-68-C3-A9-72-65-74-65-5C-22-29-2E-22-7D-2C-22-66-69-6E-69-73-68-5F-72-65-61-73-6F-6E-22-3A-22-73-74-6F-70-22-2C-22-69-6E-64-65-78-22-3A-30-7D-5D-7D'.
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadChunkFromConnectionBuffer(Int32 maxBytesToRead, CancellationTokenRegistration cancellationRegistration)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.<SerializeToStreamAsync>g__Impl|6_0(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OpenAI.Chat.ChatEndpoint.GetCompletionAsync(ChatRequest chatRequest, CancellationToken cancellationToken)
   at TestClient.Main.ProcessUserRequest(String message) in C:\[redacted]\Main.cs:line 175
```
